name: CI

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Show environment
        run: |
          echo "Hello from GitHub Actions"
          uname -a
          pwd

      - name: List files
        run: ls -la

      - name: list contents of index.html
        run: cat src/index.html
